name: Publish Kecare-tools to npm And build KecareGenerator
on:
  push:
    branches:
      - beta
jobs:
  publish-kecare-tools:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: action/checkout@v5
        
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24.8.0'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: bun install

      - name: Install Kecare-tools dependencies
        working-directory: projects/kecare-tools
        run: bun install

      - name: Publish Kecare-tools
        run: bun run publishKecare-tools

      -  name: build KecareGenerator
         run: bun run buildKecareGenerator
         env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
        
        
      
    
