name: Publish kecare-tools via trusted publishing

on:
  push:
    tags:
      - 'v*-beta.*'

permissions:
  id-token: write
  contents: write

jobs:
  publish-kecare-tools:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Ensure npm supports trusted publishing
        run: npm install -g npm@latest

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Install root dependencies
        run: bun install
      
      - name: Read package version
        working-directory: ./
        run: |
          echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      
      - name: Sync version to subpackages
        working-directory: projects/kecare-tools
        run: |
          node -e "const { readFileSync, writeFileSync } = require('fs'); const Path = './package.json'; const pkg = JSON.parse(readFileSync(Path, 'utf8')); pkg.version = process.env.VERSION; writeFileSync(Path, JSON.stringify(pkg, null, 2));"


      - name: Install kecare-tools dependencies
        working-directory: projects/kecare-tools
        run: bun install

      - name: Publish kecare-tools 
        working-directory: projects/kecare-tools
        run: npm publish --tag beta

      - name: Create dist directory
        run: mkdir -p dist

      - name: buildKecareGenerator
        run: |
            bun build ./projects/generator/index.ts --compile --target=bun-windows-x64 --outfile ./dist/kecare-generator-${{ github.ref_name }}-windows-x64.exe
             bun build ./projects/generator/index.ts --compile --target=bun-linux-x64 --outfile ./dist/kecare-generator-${{ github.ref_name }}-linux-x64

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "kecare-generator ${{ github.ref_name }} (beta)"
          prerelease: true
          generate_release_notes: true
          files: |
            ./dist/kecare-generator-${{ github.ref_name }}-windows-x64.exe
            ./dist/kecare-generator-${{ github.ref_name }}-linux-x64

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup on failure
        if: failure()
        run: |
          echo "Build or release failed. Cleaning up..."
          rm -rf dist/ || true